### ISSUE TITLE
Filter specifications: Notch and and band-stop

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#144]
Hossein, Richard:
- Add a button "View filter response" to the notch and band-stop processes 
- Create "transient" events in the filtered files, as it was done for the band-pass filter
- Update the section "Filter specifications" of the tutorial: http://neuroimage.usc.edu/brainstorm/Tutorials/ArtifactsFilter#Filters_specifications_.5BTODO.5D

Francois: 
- Update section "Apply a notch filter" to add the transients in screen capture and text (after the documentation of the notch filter)

**Comment by HosseinShahabi** [comment]
I want to draw your attention to the current band-stop filter in Brainstorm.

This filter is an 8 order Butterworth filter which mostly likes a wideband notch filter than a bandstop (1-bandpass). I've attached the magnitude and impulse response of the filter (designed for a bandstop [.2 .4]). 
![image](https://user-images.githubusercontent.com/45434165/50183542-48860180-02c7-11e9-84ed-875a0dd15e2a.png)
![image](https://user-images.githubusercontent.com/45434165/50183556-53409680-02c7-11e9-9a54-5a8acb2468d9.png)

The edge effect based on 99% energy is around 20 samples for this case. Please note that the edge effect will be doubled since we use "filtfilt". Here is my question: 
Do we want to keep this configuration or change it?

**Comment by HosseinShahabi** [comment]
Dear @ftadel 

I edited the process_bandstop by adding necessary codes and filter response panel. 
I will PR the code (Single function in this case). Once you approved the code, I'll edit the Tutorial. 
![image](https://user-images.githubusercontent.com/45434165/50622490-6441f800-0ec2-11e9-9f09-720bd5e33e7f.png)

The process_notch needs further work since we are modifying the algorithm.

**Comment by HosseinShahabi** [comment]
Both are set. 
https://github.com/brainstorm-tools/brainstorm3/pull/158

**Comment by ftadel** [comment]
Have you modified the code for the notch and bandstop filters?
If so, it would be good to discuss it with @sbaillet @richardmleahy @jcmosher and @dimitriospantazis before pushing them to the Brainstorm distribution.
To be added to the agenda of a biweekly meeting?

**Comment by sbaillet** [comment]
that was indeed the plan.

Best wishes,

Sylvain.
-
Sylvain Baillet, PhD
Professor, Montreal Neurological Institute
McGill University
> more<https://goo.gl/591JdQ>

On Jan 15, 2019, at 9:59 AM, Francois <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you modified the code for the notch and bandstop filters?
If so, it would be good to discuss it with @sbaillet<https://github.com/sbaillet> @richardmleahy<https://github.com/richardmleahy> @jcmosher<https://github.com/jcmosher> and @dimitriospantazis<https://github.com/dimitriospantazis> before pushing them to the Brainstorm distribution.
To be added to the agenda of a biweekly meeting?

**Comment by ftadel** [comment]
Fixed with the PR 177
