### ISSUE TITLE
EZ Fingerprint software

### ISSUE THREAD

**Issue by silencer1127** [brainstorm-tools/brainstorm3#157]
Allow users to run the EZ Fingerprint software directly from the Brainstorm. Here is the full documentation:

[EZFingerprint](https://silencer1127.github.io/software/EZ_Fingerprint/ezf_main)

The software is self-contained with both a front-end interface and a back-end server implementation. It has been released publicly about half a year ago and it is currently being used by people. For these reasons, I suggest find a proper place in the Brainstorm interface and add a button or a menu item to call the main function of the EZ Fingerprint. This is also the easiest way to integrate.

**Comment by ftadel** [comment]
This page doesn't load: http://imagicastle.com:27224/software/download.php?app=ezf
It might be a firewall problem, but I tried from two networks and could not get anything.

**Comment by ftadel** [comment]
I finally managed to access it using the 4G connection of my cell phone. 

1) The registration page was blocked from both the hospital eduroam and the university networks, so other people might struggle. 

2) There will be some major distribution incompatilibity between your new interface and the rest of the software:
- The entire Brainstorm distribution is supported up to Matlab 2008a while you need Matlab >= 2016b (see: https://neuroimage.usc.edu/brainstorm/Installation)
- Brainstorm runs entirely without any additional toolbox (we try to make this accessible to as many users as possible, and unfortunately it's only in North America that all the toolboxes are available campus-wide...). Even the signal processing toolbox is an option, we made important efforts in the past years to write free alternatives to all the sigproc tb functions, most of them coming from Octave (see all the oc_* functions, bst_window.m, etc...)
- I don't have myself the image processing toolbox installed anywhere. I could install it, but first I'd like to ask what you need it for. This toolbox is usually a lot easier to get rid of than the signal processing one.

3) Adding the add didn't work on my Matlabs 2018a, 2017b, or 2016b. When I click on "Install app" and select your installer EZ_Fingerprint.mlappinstall, it just hangs forever, I need to kill Matlab. It only worked with the Matlab 2019a prerelease. I have the same install configuration for all the versions (MATLAB, MATLAB Compiler, Signal Processing Toolbox, on Windows 10). I have never worked with Matlab apps so I don't know how to debug this... 

4) Where do we get the tutorial dataset from? How do we import it to Brainstorm? A tutorial with no example to reproduce and that starts half-way into the analysis is unfortunately a bit difficult to follow... (other than that, the documentation looks good!)

5) Since the registration, the distribution mechanism, the software requirements, the code repository, the interface, the documentation are separate from Brainstorm, I would say this is a fully independent tool. It is downloaded as a Matlab app and not as a Brainstorm module, so we cannot even add an automatic downloader in the process list (like we did with the CENA, BEST/MEM or NIRSTORM libraries). One thing you can do to attract Brainstorm users to your software would be to write a page on the Brainstorm website, just to reference your project. Create a new page on the wiki and add a link "SEEG seizure analysis: EZ Fingerprint" in the section "Advanced processing" in https://neuroimage.usc.edu/brainstorm/Tutorials.

--

@richardmleahy @jcmosher  I'm not sure I understand why this was developed completely outside of Brainstorm, not discussing the implentation choices, not using our github repo, registration, distribution or interfacing mechanisms... Integrating it now would mean rewriting mostly everything, this is not realistic. This might be development time well invested in creating something useful and good looking for the SEEG/epilespy community, but it does not contribute to Brainstorm, it's a separate project, I cannot build on it for my future SEEG developments with my European colleagues. 
Not being integrated to our code repo and distribution system also means that when Brainstorm evolves, this software will not get updated with it. Typically, when Sylvain and Martin release a new databasing system, this interface will stop working and will need some rewriting from your end. The maintenance over the years will be complicated. 
Before starting any new developments, please ask your collaborators to discuss first the overview of the implementation with Martin, Sylvain and I, so that we all work in the same direction.

**Comment by ftadel** [comment]
Integration done in: 
https://github.com/brainstorm-tools/brainstorm3/pull/167
