### ISSUE TITLE
Selecting more than one Electrode causes error

### ISSUE THREAD

**Issue by jcmosher** [brainstorm-tools/brainstorm3#184]
To reproduce the error (either Mac or Windows), display SEEG electrodes on cortex, go to iEEG tab, select one electrode, then use "shift A" or "control A" to select multiple electrode, yields consistently the error

***************************************************************************
** Error: Line 2253:  isempty
** Too many input arguments.
** 
** Call stack:
** >panel_ieeg.m>CenterMriOnElectrode at 2253
** >panel_ieeg.m>CreatePanel/ElecListValueChanged_Callback at 268
** >bst_call.m at 28
** >panel_ieeg.m>@(h,ev)bst_call(@ElecListValueChanged_Callback,h,ev) at 91
** 
***************************************************************************

The relevant lines in panel_ieeg.m are

    % If tip of electrode not defined: return
    if isempty(sElec) || isempty(sElec.Loc) || isequal(sElec.Loc(:,1), [0;0;0])
        return;
    end

The issue is that sElec is a struct array for the number of electrodes selected, and isempty(sElec.Loc) is invalid. 
isequal(sElec.Loc(:,1), [0;0;0]) is also invalid.

I leave it to experts to fix.

**Comment by ftadel** [comment]
Fixed in: https://github.com/brainstorm-tools/brainstorm3/commit/fbf0503e844d257ec3ada74aef71d3a14259e52e

New documentation section: https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity#A2D_topography

![image](https://user-images.githubusercontent.com/6920058/54399504-0a7a5d00-46bf-11e9-81ec-0f729e6415be.png)
