### ISSUE TITLE
File selection fails for PTE files when trying to average

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#227]
I computed PTE files from a sliding window as shown on the following image:

![image](https://user-images.githubusercontent.com/23224563/62804886-833de380-babc-11e9-8999-eeb6bf9fa189.png)

I want to average the PTE files based on each window (that's why I select (-450, -100) on the filter).
However, when I select the average function, I get this error:

***************************************************************************
** Error: [process_average]  Average > Average files
** Line 33:  fileparts (line 33)
** Input must be a row vector of characters.
** 
** Call stack:
** >fileparts.m at 33
** >bst_get.m>findFileInStudies at 3693
** >bst_get.m at 1478
** >process_average.m>SortFiles at 260
** >process_average.m>Run at 173
** >process_average.m at 29
** >bst_process.m>Run at 229
** >bst_process.m at 36
** >panel_process1.m>RunProcess at 151
** >panel_process1.m at 26
** >gui_brainstorm.m>CreateWindow/ProcessRun_Callback at 760
** >bst_call.m at 28
** >gui_brainstorm.m>@(h,ev)bst_call(@ProcessRun_Callback) at 293
** 
** 
***************************************************************************

My understanding is that the file selection from the tree fails when the filter string is applied.
Any thoughts?

K.

**Comment by martcous** [comment]
As discussed offline, the issue was not with the filter but rather the Average process option to group by trial groups: as seen in the screenshot, the PTE files were not under any trial group so an unexpected null value made things crash down the line.

The issue is resolved if the user chooses to average everything instead. I made the function null-safe so that the user gets a warning that the file is skipped instead if no trial group is found: https://github.com/brainstorm-tools/brainstorm3/commit/3aef22bf810e0a1a2a0edd3bc2ca47d2add53c50

Thanks for the report!
Martin
