### ISSUE TITLE
Update The Neuro logo on spash screen

### ISSUE THREAD

**Issue by Moo-Marc** [brainstorm-tools/brainstorm3#258]
Low priority, but available here:
https://mcgill.ca/neuro/visual-identity-guide-and-templates

**Comment by sbaillet** [comment]
👍


On Feb 7, 2020, at 11:28 AM, Marc Lalancette <notifications@github.com<mailto:notifications@github.com>> wrote:


Low priority, but available here:
https://mcgill.ca/neuro/visual-identity-guide-and-templates

**Comment by ftadel** [comment]
I also removed the Cleveland Clinic logo and added the UTHealth one:
![image](https://user-images.githubusercontent.com/6920058/74144393-f0157000-4bfc-11ea-8fd3-2abc6fe72b45.png)

**Comment by juangpc** [comment]
Thanks, on behalf of UThealth!

Since this logo-talking has already started... one question. MD's I work with, find kind of odd that the binary version of BST is a batch script file with no logo. I usually create a desktop link for them, but still, is this intentional? or if I find the time and push a logo-ed script will it be included? Just asking. Nothing really important. Thanks.

**Comment by ftadel** [comment]
I'm not sure what you mean with "a logo-ed batch script".
We could add a link (.lnk file, like you desktop link, which can reference an icon) on top of the existing .jar and calling scripts for Windows (.bat) and Linux/MacOS (.command). But I think that it would be even more confusing to have both the .lnk and .bat files.

The proper Windows approach would be rather to have an installer that creates the desktop and start menu links. But then it makes the updates possibly a bit more complicated...
