### ISSUE TITLE
screen scaling 

### ISSUE THREAD

**Issue by juangpc** [brainstorm-tools/brainstorm3#331]
Hi, 

I would like to share my experience on the automatic screen scaling applied to a BS fresh install. 

When installing it in a mac book pro (in its default configuration), through the code referenced in the following link, 
the scaling value is 150. It is definitely not bad, but it seems really too big. 

When installing BS in a windows10 computer with a 27' screen (specifically with 2560x1440 and 0.233mm2 pixel pitch) it also configures a default scaling value of 150.

 https://github.com/brainstorm-tools/brainstorm3/blob/f8c0a79b018e39c3bccb7a1093e96b42207587fb/toolbox/core/bst_get.m#L2597

In both cases, I think there is nothing bad with it. But I don't see the need for this. For the new user, the first impression of BS's GUI is that it is quite amateur, or similar.

Business as usual. If this is not helpful, please delete this issue. I'm only trying to help. No issue, on my side (pun). 

Juan

**Comment by ftadel** [comment]
The problem is that it is difficult to have access to the screen resolution in a reliable way in Matlab.
With 2560x1440 on a 15" laptop, you'd probably want to zoom at 150%. But on a 27' screen, you don't need to.

It is maybe better to start small and zoom in than the contrary.
But on the other hand, I've have so many people complaining about the text being too small for so many years...

I changed the target to 1920px=100%, which will give 125% on your screen, and we'll see if anybody complains.
https://github.com/brainstorm-tools/brainstorm3/commit/7f7bcfa65873c0bc1bff239c67ded6b9fe4e42e7
