### ISSUE TITLE
Auto-loading .fif file from command line

### ISSUE THREAD

**Issue by soichih** [brainstorm-tools/brainstorm3#377]
We are trying to use brainstorm3 as a visualization tool for our MEG data, and I am currently trying to figure out how I can open a specific .fif file from a command line so that user doesn't have to manually navigate to the data and load / open UIs themselves.

Is there a way to do something like.

`brainstorm3.command  -fif /input/meg.fif`

Or even..

`brainstorm3.command -create_protocol vis -create_subject vis -fif /input/meg.fif`

??

I believe I can just save the content of ~/.brainstorm and use it for all visualization session to repopulate the protocol / subject structure, so I don't think I really need -create_protocol / -create_subject type command line options, but I still need to load specific data under the subject for different visualization sessions from command line. Is there a way to script this somehow, and execute that script at boot time?

Also, I've noticed that any UIs that I open once I load the .fif file is not persited across reboot. Is there a way to store the current UI session and re-store it?

**Comment by ftadel** [comment]
Welcome!

Brainstorm does not offer any standalone file viewer, or any other interface that can be used independently from its database.
If you want to display a FIF file in Brainstorm, you need to go through all the steps illustrated in the introduction tutorials (section "Get started" in https://neuroimage.usc.edu/brainstorm/Tutorials):
- create a protocol,
- create a subject, 
- define its anatomy (the ICBM152 template if you don't need any realistic 3D modelling or display)
- link the FIF file to the subject
- review this file link

It is possible to automate all this with a script, and make it transparent to your user (create a temporary subject that is deleted at the end of the session or at the beginning of the next one). Scripting with Brainstorm is introduced in the last introduction tutorial, and is illustrated in all the scripts in `brainstorm3/toolbox/scripts/`:
https://neuroimage.usc.edu/brainstorm/Tutorials/Scripting

You seem to be interested in using the compiled version of Brainstorm. It makes things a bit more complicated and less interactive, but still doable. This is to be considered only if you don't have access to a Matlab license. 
You need to write all your commands in a .m script and call them from the command line:
https://neuroimage.usc.edu/brainstorm/Tutorials/Scripting#Starting_Brainstorm

Please note that we prefer handling questions related to the **use** of Brainstorm, such as this one, from the Brainstorm user forum, since it is much easier to search through by other users. Many users receive notifications when new messages are posted on the forum, while only developers get the github issues - Thanks
https://neuroimage.usc.edu/forums/

If there are tools that you need and you are interested in contribute directly to the software, you are more than welcome to open PRs here! If you want to make modifications to the compiled distribution, I'd recommend you start by prototyping it from Matlab, and then I'll help you go through the compilation process.
