### ISSUE TITLE
Cluster senors in TF and grouping times in Time series

### ISSUE THREAD

**Issue by guiomar** [brainstorm-tools/brainstorm3#545]
Hi!

Is there a way to cluster sensors in TF maps? I see there's the option to cluster the time series, but not for TF maps. Should I need to do it for the time series and then compute again the TF?

Similar, is there a way to group in time bands for time series? I see there's an option to group in time and frequency bands for TF maps, but not for time series.

Thanks!

**Comment by ftadel** [comment]
> Is there a way to cluster sensors in TF maps? 

You can use the process `Extract values` to select some sensors and average their TF response together:
![image](https://user-images.githubusercontent.com/6920058/168086036-7d1947d9-2d49-42b3-b17d-b0d72e45a3fb.png)

This must be done separately for each cluster. 

> Should I need to do it for the time series and then compute again the TF?

This would produce something very different. 
Similarly to averaging trials, you should probably average the TF power instead of compute the TF of the average across sensors.

> is there a way to group in time bands for time series?

No. The "data" or "matrix" file structures  do not have any information for grouping by time bands. 
 https://neuroimage.usc.edu/brainstorm/Tutorials/Epoching#On_the_hard_drive

You can use the process `Average time` to compute the average over a time window.


For usage questions, the forum is maybe more adapted, as it is where users look for answers first. Thanks.

**Comment by guiomar** [comment]
Thanks @ftadel !! I have copied the thread on the forum in case it can help someone else :)

Ok. Makes sense. The advantage of having everything in one file together is that it's easier to manage and do stats, etc. But these are quite remote cases, so it's not worth the effort. The windowing of time series, could be done more easily though if for example we average the signals across the windows and keep as time the middle point of the windows, so it doesn't need any extra field like for the frequency bands. But again, I can do this manually and probably no more need for it from other users for a official implementation.

**Comment by ftadel** [comment]
> The windowing of time series, could be done more easily though if for example we average the signals across the windows and keep as time the middle point of the windows, so it doesn't need any extra field like for the frequency bands. 

You can create multiple averages, and use the process "Concatenate time" to group them.
